#!/bin/sh

case $1 in
    scan)
        echo '[{"Type":"sample","Name":"myunit","Dependencies":[{"name":"mydep"}],"Ops":{"graph":null,"depresolve":null}}]'
        ;;
    graph)
        echo '{"Defs":[{"Repo":"","UnitType":"sample","Unit":".","Path":"mydef","Name":"mydef","File":"f","DefStart":123,"DefEnd":456,"Exported":true,"Kind":"var","TreePath":"mydef"}],"Refs":[],"Docs":[]}'
        ;;
    depresolve)
        echo '[{"Raw":{"name":"mydep"},"Target":{"ToRepoCloneURL":"https://github.com/example/repo"}}]'
        ;;
    *)
        echo Unknown command: $1 >&2
        exit 1
        ;;
esac
